#!/usr/bin/env python
"""Script to call local installation of `mypy`.

Script considers OS and calls mypy accordingly.
"""

import subprocess
import sys


def main():
    """Call mypy"""
    if sys.platform == "win32":
        cmd = (".tox/pre-commit/Scripts/mypy.exe", *sys.argv[1:])
    else:
        cmd = (".tox/pre-commit/bin/mypy", *sys.argv[1:])
    return subprocess.call(cmd)


if __name__ == "__main__":
    sys.exit(main())
