#!/usr/bin/env python
"""Script to call local installation of `pylint`.

Script considers OS and calls pylint accordingly.
"""

import subprocess
import sys


def main():
    """Call pylint"""
    if sys.platform == "win32":
        cmd = (".tox/pre-commit/Scripts/pylint.exe", *sys.argv[1:])
    else:
        cmd = (".tox/pre-commit/bin/pylint", *sys.argv[1:])
    return subprocess.call(cmd)


if __name__ == "__main__":
    sys.exit(main())
